server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: gymly
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:15}
    refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS:7}
    issuer: gymly

admin:
  password: ${ADMIN_RAW_PASSWORD}

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN}
