DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'membership_status') THEN
CREATE TYPE membership_status AS ENUM ('active', 'expired', 'frozen');
END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
CREATE TYPE payment_status AS ENUM ('successful', 'pending', 'rejected');
END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
CREATE TYPE payment_method AS ENUM ('cash', 'card', 'transfer');
END IF;
END $$;

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id integer NOT NULL,
    name varchar NOT NULL,
    last_name varchar NOT NULL,
    document varchar NOT NULL UNIQUE,
    phone varchar UNIQUE,
    email varchar UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz DEFAULT (now()),
    active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description text,
    duration_days integer NOT NULL,
    price numeric(10,2) NOT NULL,
    active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS discounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    percentage numeric(5,2) NOT NULL,
    init_date date NOT NULL,
    end_date date NOT NULL,
    active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS memberships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    plan_id integer NOT NULL,
    init_date date NOT NULL,
    end_date date NOT NULL,
    status membership_status DEFAULT 'active',
    created_at timestamptz DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS attendances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    date timestamptz DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id integer NOT NULL,
    user_id integer NOT NULL,
    discount_id integer,
    amount numeric(10,2) NOT NULL,
    method payment_method DEFAULT 'cash',
    reference text,
    status payment_status DEFAULT 'pending',
    created_at timestamptz DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    token text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS notification_queue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    message text NOT NULL,
    alert_type varchar NOT NULL,
    processed boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT (now())
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_user_role' AND table_name = 'users' AND table_schema = 'public') THEN
ALTER TABLE users ADD CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_membership_user' AND table_name = 'memberships' AND table_schema = 'public') THEN
ALTER TABLE memberships ADD CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_membership_plan' AND table_name = 'memberships' AND table_schema = 'public') THEN
ALTER TABLE memberships ADD CONSTRAINT fk_membership_plan FOREIGN KEY (plan_id) REFERENCES plans (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_attendance_user' AND table_name = 'attendances' AND table_schema = 'public') THEN
ALTER TABLE attendances ADD CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_payment_membership' AND table_name = 'payments' AND table_schema = 'public') THEN
ALTER TABLE payments ADD CONSTRAINT fk_payment_membership FOREIGN KEY (membership_id) REFERENCES memberships (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_payment_user' AND table_name = 'payments' AND table_schema = 'public') THEN
ALTER TABLE payments ADD CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_payment_discount' AND table_name = 'payments' AND table_schema = 'public') THEN
ALTER TABLE payments ADD CONSTRAINT fk_payment_discount FOREIGN KEY (discount_id) REFERENCES discounts (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_refresh_token_user' AND table_name = 'refresh_tokens' AND table_schema = 'public') THEN
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_notification_queue_user' AND table_name = 'notification_queue' AND table_schema = 'public') THEN
ALTER TABLE notification_queue ADD CONSTRAINT fk_notification_queue_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;
END $$;