DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'membership_status') THEN
CREATE TYPE membership_status AS ENUM ('active', 'expired', 'frozen');
END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
CREATE TYPE payment_status AS ENUM ('successful', 'pending', 'rejected');
END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method') THEN
CREATE TYPE payment_method AS ENUM ('cash', 'card', 'transfer');
END IF;
END $$;

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id integer NOT NULL,
    name varchar NOT NULL,
    lastname varchar NOT NULL,
    document integer NOT NULL UNIQUE,
    phone varchar UNIQUE,
    mail varchar UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz DEFAULT (now()),
    active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description text,
    duration_days integer NOT NULL,
    price numeric(10,2) NOT NULL,
    active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS discount (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    percentage numeric(5,2) NOT NULL,
    init_date date NOT NULL,
    end_date date NOT NULL,
    active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS membership (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    plan_id integer NOT NULL,
    init_date date NOT NULL,
    end_date date NOT NULL,
    status membership_status DEFAULT 'active',
    created_at timestamptz DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    date timestamptz DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS payment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id integer NOT NULL,
    user_id integer NOT NULL,
    discount_id integer,
    amount numeric(10,2) NOT NULL,
    method payment_method DEFAULT 'cash',
    reference text,
    status payment_status DEFAULT 'pending',
    created_at timestamptz DEFAULT (now())
);

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_user_role' AND table_name = 'users' AND table_schema = 'public') THEN
ALTER TABLE users ADD CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES roles (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_membership_user' AND table_name = 'membership' AND table_schema = 'public') THEN
ALTER TABLE membership ADD CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_membership_plan' AND table_name = 'membership' AND table_schema = 'public') THEN
ALTER TABLE membership ADD CONSTRAINT fk_membership_plan FOREIGN KEY (plan_id) REFERENCES plan (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_attendance_user' AND table_name = 'attendance' AND table_schema = 'public') THEN
ALTER TABLE attendance ADD CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_payment_membership' AND table_name = 'payment' AND table_schema = 'public') THEN
ALTER TABLE payment ADD CONSTRAINT fk_payment_membership FOREIGN KEY (membership_id) REFERENCES membership (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_payment_user' AND table_name = 'payment' AND table_schema = 'public') THEN
ALTER TABLE payment ADD CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users (id);
END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_payment_discount' AND table_name = 'payment' AND table_schema = 'public') THEN
ALTER TABLE payment ADD CONSTRAINT fk_payment_discount FOREIGN KEY (discount_id) REFERENCES discount (id);
END IF;
END $$;